### ISSUE TITLE
Undefined index: X-GitHub-

### ISSUE THREAD

**Issue by ghost** [dintel/php-github-webhook#2]
I am getting these notices, yet according to the github webhook audit trail the headers match what you are looking for.

But then I did my own tests using apache_request_headers() 
and the array I got returned has X-Github- headers. Notice the lowercase h in github

I am just wondering if this code has actually been tested and works, or if there is some configuration on my server that is causing this to happen

PHP Notice:  Undefined index: X-GitHub-Event in vendor\dintel\php-github-webhook\src\Handler.php on line 76
PHP Notice:  Undefined index: X-GitHub-Delivery in vendor\dintel\php-github-webhook\src\Handler.php on line 77
PHP Notice:  Undefined index: X-GitHub-Event in dintel\php-github-webhook\src\Handler.php on line 76
PHP Notice:  Undefined index: X-GitHub-Delivery in vendor\dintel\php-github-webhook\src\Handler.php on line 77

**Comment by dintel** [comment]
I tested it and it worked for my project.
Also checked now again and it looks like that on my server apache_request_headers() returns headers with uppercase h in github, like:
'X-GitHub-Event' => 'ping'
So it's really strange. May be it's GitHub that sends wrong headers?

**Comment by dintel** [comment]
I fixed the issue and released new version.
This script should be now case-insensitive in header names.

**Comment by ghost** [comment]
Thanks
