### ISSUE TITLE
Changes are not showing

### ISSUE THREAD

**Issue by MarcTowler** [dintel/php-github-webhook#3]
I have just started to use this script and I have been running into a fundamental issue, when I push to github, the webhook runs and gets a 200 response back but the exec() function seems to just not work.
None of the changes files in the repo are updated by the script, I have checked the error logs and none are reported, exec() is not disabled, the actual git command when run manually works perfectly fine just not via the webhook, any ideas?

**Comment by dintel** [comment]
You can try to log git output.
Just add something like this after calling to Handler::handle()
file_put_contents("/tmp/git.log", $handler->getGitOutput(), FILE_APPEND);

**Comment by MarcTowler** [comment]
will do

**Comment by MarcTowler** [comment]
i have added it in and the git.log file has been created but it stays empty even after 10 commits

**Comment by dintel** [comment]
Git can output to stderr, instead of stdout. Try to change exec like this:
exec("git --work-tree={$this->gitDir} pull -f {$this->remote} 2>&1", $this->gitOutput);

**Comment by MarcTowler** [comment]
thanks this helped me find out that it was a permissions error so I am closing this thank you
